[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nba"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = [
#    "requests",
#    "numpy",
#    "pandas",
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]